# Generated by Django 3.2.7 on 2021-10-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='avatar',
        ),
    ]
