# Generated by Django 3.2.7 on 2021-09-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, unique=True)),
                ('brand_country', models.CharField(max_length=30)),
                ('brand_history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, unique=True)),
                ('model_brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_year', models.IntegerField()),
                ('car_price', models.IntegerField()),
                ('car_engine_type', models.CharField(choices=[('GAS', 'Бензиновый двигатель'), ('DIE', 'Дизельный двигатель'), ('ELE', 'Электродвигатель')], default='GAS', max_length=3)),
                ('car_engine_capacity', models.FloatField(max_length=3)),
                ('car_engine_power', models.IntegerField()),
                ('car_transmission_type', models.CharField(choices=[('MAN', 'Ручная коробка передач'), ('AUT', 'Автоматическая коробка передач'), ('ROB', 'Роботизированная коробка передач'), ('VAR', 'Бесступенчатая коробка передач (вариатор)')], default='MAN', max_length=3)),
                ('car_drive', models.CharField(choices=[('FRO', 'Передний привод'), ('REA', 'Задний привод'), ('ALL', 'Полный привод')], default='FRO', max_length=3)),
                ('car_color', models.CharField(choices=[('RED', 'Красный'), ('GRE', 'Зелёный'), ('BLU', 'Синий'), ('WHI', 'Белый'), ('BLA', 'Чёрный'), ('YEL', 'Жёлтый')], default='WHI', max_length=3)),
                ('car_mileage', models.IntegerField()),
                ('car_wheel', models.CharField(choices=[('LEF', 'Левый руль'), ('RIG', 'Правый руль')], default='LEF', max_length=3)),
                ('car_vin', models.IntegerField(unique=True)),
                ('car_description', models.TextField()),
                ('car_image', models.ImageField(upload_to='')),
                ('car_date_create', models.DateTimeField(auto_now_add=True)),
                ('car_brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
                ('car_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.city')),
                ('car_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.model')),
            ],
        ),
    ]
