# Generated by Django 3.2.7 on 2021-09-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(choices=[('RED', 'Красный'), ('GRE', 'Зелёный'), ('BLU', 'Синий'), ('WHI', 'Белый'), ('BLA', 'Чёрный'), ('YEL', 'Жёлтый')], default='WHI', max_length=3, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_drive',
            field=models.CharField(choices=[('FRO', 'Передний привод'), ('REA', 'Задний привод'), ('ALL', 'Полный привод')], default='FRO', max_length=3, verbose_name='Тип привода'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_engine_capacity',
            field=models.FloatField(max_length=3, verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_engine_power',
            field=models.IntegerField(verbose_name='Мощность л.с.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_engine_type',
            field=models.CharField(choices=[('GAS', 'Бензиновый двигатель'), ('DIE', 'Дизельный двигатель'), ('ELE', 'Электродвигатель')], default='GAS', max_length=3, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_mileage',
            field=models.IntegerField(verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_price',
            field=models.IntegerField(verbose_name='Стоимость автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_transmission_type',
            field=models.CharField(choices=[('MAN', 'Ручная коробка передач'), ('AUT', 'Автоматическая коробка передач'), ('ROB', 'Роботизированная коробка передач'), ('VAR', 'Бесступенчатая коробка передач (вариатор)')], default='MAN', max_length=3, verbose_name='Тип трансмиссии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_vin',
            field=models.IntegerField(unique=True, verbose_name='VIN номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_wheel',
            field=models.CharField(choices=[('LEF', 'Левый руль'), ('RIG', 'Правый руль')], default='LEF', max_length=3, verbose_name='Руль'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_brand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.brand'),
        ),
    ]
