# Generated by Django 3.2.7 on 2021-09-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210926_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(null=True, upload_to='cars/', verbose_name='Фото'),
        ),
    ]
