# Generated by Django 3.2.7 on 2021-09-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210927_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
    ]
