# Generated by Django 3.2.7 on 2021-10-10 14:19

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20211002_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='car_brand', chained_model_field='Brand', on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель'),
        ),
    ]
