# Generated by Django 3.2.7 on 2021-10-11 00:58

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='car_brand', chained_model_field='model_brand_id', on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель'),
        ),
    ]
